// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LifecycleStage struct {
	ID            int64              `json:"id"`
	DtCreated     pgtype.Timestamptz `json:"dt_created"`
	DtUpdated     pgtype.Timestamptz `json:"dt_updated"`
	Name          string             `json:"name"`
	IsActive      bool               `json:"is_active"`
	ModLuminosity int32              `json:"mod_luminosity"`
	ModTemp       int32              `json:"mod_temp"`
}

type LuminosityClass struct {
	ID             int64              `json:"id"`
	DtCreated      pgtype.Timestamptz `json:"dt_created"`
	DtUpdated      pgtype.Timestamptz `json:"dt_updated"`
	Numeral        string             `json:"numeral"`
	Name           string             `json:"name"`
	MassModifier   int32              `json:"mass_modifier"`
	RadiusModifier int32              `json:"radius_modifier"`
}

type SpectralClass struct {
	ID            int64              `json:"id"`
	DtCreated     pgtype.Timestamptz `json:"dt_created"`
	DtUpdated     pgtype.Timestamptz `json:"dt_updated"`
	Letter        string             `json:"letter"`
	Subtype       int16              `json:"subtype"`
	Name          string             `json:"name"`
	MinTemp       int32              `json:"min_temp"`
	MaxTemp       int32              `json:"max_temp"`
	MinMass       int32              `json:"min_mass"`
	MaxMass       int32              `json:"max_mass"`
	MinLuminosity int32              `json:"min_luminosity"`
	MaxLuminosity int32              `json:"max_luminosity"`
	MinRadius     int32              `json:"min_radius"`
	MaxRadius     int32              `json:"max_radius"`
}

type Star struct {
	ID                int64              `json:"id"`
	DtCreated         pgtype.Timestamptz `json:"dt_created"`
	DtUpdated         pgtype.Timestamptz `json:"dt_updated"`
	Name              string             `json:"name"`
	IDSpectralClass   int64              `json:"id_spectral_class"`
	IDLuminosityClass int64              `json:"id_luminosity_class"`
	IDLifecycleStage  int64              `json:"id_lifecycle_stage"`
	Mass              int32              `json:"mass"`
	Radius            int32              `json:"radius"`
	Temp              int32              `json:"temp"`
	Luminosity        int32              `json:"luminosity"`
	Metallicity       int32              `json:"metallicity"`
	Age               int32              `json:"age"`
	FlareFrequency    int16              `json:"flare_frequency"`
	SolarWind         int16              `json:"solar_wind"`
	Variability       int16              `json:"variability"`
	HabitableInner    int32              `json:"habitable_inner"`
	HabitableOuter    int32              `json:"habitable_outer"`
	FrostLine         int32              `json:"frost_line"`
	PosX              int32              `json:"pos_x"`
	PosY              int32              `json:"pos_y"`
	PosZ              int32              `json:"pos_z"`
	Pos               []byte             `json:"pos"`
}

type System struct {
	ID        int64              `json:"id"`
	DtCreated pgtype.Timestamptz `json:"dt_created"`
	DtUpdated pgtype.Timestamptz `json:"dt_updated"`
	Name      string             `json:"name"`
	PosX      int32              `json:"pos_x"`
	PosY      int32              `json:"pos_y"`
	PosZ      int32              `json:"pos_z"`
	Pos       []byte             `json:"pos"`
}

type SystemStar struct {
	IDSystem      int64              `json:"id_system"`
	IDStar        int64              `json:"id_star"`
	DtCreated     pgtype.Timestamptz `json:"dt_created"`
	DtUpdated     pgtype.Timestamptz `json:"dt_updated"`
	SemiMajorAxis int32              `json:"semi_major_axis"`
	Eccentricity  int32              `json:"eccentricity"`
	Inclination   int32              `json:"inclination"`
	OrbitalPeriod int32              `json:"orbital_period"`
	IsPrimary     bool               `json:"is_primary"`
}
