// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stars.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSystemStars = `-- name: CountSystemStars :one
SELECT COUNT(*) FROM system_star WHERE id_system = $1
`

func (q *Queries) CountSystemStars(ctx context.Context, idSystem int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSystemStars, idSystem)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findNearestStars = `-- name: FindNearestStars :many
SELECT s.id, s.name, s.temp, s.luminosity, s.mass,
       s.pos_x, s.pos_y, s.pos_z,
       (s.pos <-> ST_MakePoint($1::float8, $2::float8, $3::float8))::integer AS dist
FROM star s
ORDER BY s.pos <-> ST_MakePoint($1::float8, $2::float8, $3::float8)
LIMIT $4
`

type FindNearestStarsParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Limit   int32   `json:"limit"`
}

type FindNearestStarsRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Temp       int32  `json:"temp"`
	Luminosity int32  `json:"luminosity"`
	Mass       int32  `json:"mass"`
	PosX       int32  `json:"pos_x"`
	PosY       int32  `json:"pos_y"`
	PosZ       int32  `json:"pos_z"`
	Dist       int32  `json:"dist"`
}

func (q *Queries) FindNearestStars(ctx context.Context, arg FindNearestStarsParams) ([]FindNearestStarsRow, error) {
	rows, err := q.db.Query(ctx, findNearestStars,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearestStarsRow{}
	for rows.Next() {
		var i FindNearestStarsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Temp,
			&i.Luminosity,
			&i.Mass,
			&i.PosX,
			&i.PosY,
			&i.PosZ,
			&i.Dist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNearestSystems = `-- name: FindNearestSystems :many
SELECT sys.id, sys.name,
       sys.pos_x, sys.pos_y, sys.pos_z,
       (sys.pos <-> ST_MakePoint($1::float8, $2::float8, $3::float8))::integer AS dist
FROM system sys
ORDER BY sys.pos <-> ST_MakePoint($1::float8, $2::float8, $3::float8)
LIMIT $4
`

type FindNearestSystemsParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Limit   int32   `json:"limit"`
}

type FindNearestSystemsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	PosX int32  `json:"pos_x"`
	PosY int32  `json:"pos_y"`
	PosZ int32  `json:"pos_z"`
	Dist int32  `json:"dist"`
}

func (q *Queries) FindNearestSystems(ctx context.Context, arg FindNearestSystemsParams) ([]FindNearestSystemsRow, error) {
	rows, err := q.db.Query(ctx, findNearestSystems,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearestSystemsRow{}
	for rows.Next() {
		var i FindNearestSystemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PosX,
			&i.PosY,
			&i.PosZ,
			&i.Dist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findStarsWithinRadius = `-- name: FindStarsWithinRadius :many

SELECT s.id, s.name, s.temp, s.luminosity, s.mass,
       s.pos_x, s.pos_y, s.pos_z,
       ST_3DDistance(s.pos, ST_MakePoint($1::float8, $2::float8, $3::float8))::integer AS dist
FROM star s
WHERE ST_3DDWithin(s.pos, ST_MakePoint($1::float8, $2::float8, $3::float8), $4::float8)
ORDER BY dist
`

type FindStarsWithinRadiusParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Column4 float64 `json:"column_4"`
}

type FindStarsWithinRadiusRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Temp       int32  `json:"temp"`
	Luminosity int32  `json:"luminosity"`
	Mass       int32  `json:"mass"`
	PosX       int32  `json:"pos_x"`
	PosY       int32  `json:"pos_y"`
	PosZ       int32  `json:"pos_z"`
	Dist       int32  `json:"dist"`
}

// ===================
// SPATIAL QUERIES
// ===================
// Uses the generated pos column + GiST index for spatial filtering,
// but returns integer coordinates only.
func (q *Queries) FindStarsWithinRadius(ctx context.Context, arg FindStarsWithinRadiusParams) ([]FindStarsWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, findStarsWithinRadius,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindStarsWithinRadiusRow{}
	for rows.Next() {
		var i FindStarsWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Temp,
			&i.Luminosity,
			&i.Mass,
			&i.PosX,
			&i.PosY,
			&i.PosZ,
			&i.Dist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSystemsWithinRadius = `-- name: FindSystemsWithinRadius :many
SELECT sys.id, sys.name,
       sys.pos_x, sys.pos_y, sys.pos_z,
       ST_3DDistance(sys.pos, ST_MakePoint($1::float8, $2::float8, $3::float8))::integer AS dist
FROM system sys
WHERE ST_3DDWithin(sys.pos, ST_MakePoint($1::float8, $2::float8, $3::float8), $4::float8)
ORDER BY dist
`

type FindSystemsWithinRadiusParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Column4 float64 `json:"column_4"`
}

type FindSystemsWithinRadiusRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	PosX int32  `json:"pos_x"`
	PosY int32  `json:"pos_y"`
	PosZ int32  `json:"pos_z"`
	Dist int32  `json:"dist"`
}

func (q *Queries) FindSystemsWithinRadius(ctx context.Context, arg FindSystemsWithinRadiusParams) ([]FindSystemsWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, findSystemsWithinRadius,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSystemsWithinRadiusRow{}
	for rows.Next() {
		var i FindSystemsWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PosX,
			&i.PosY,
			&i.PosZ,
			&i.Dist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpectralClass = `-- name: GetSpectralClass :one
SELECT id, dt_created, dt_updated, letter, subtype, name, min_temp, max_temp, min_mass, max_mass, min_luminosity, max_luminosity, min_radius, max_radius FROM spectral_class WHERE id = $1
`

func (q *Queries) GetSpectralClass(ctx context.Context, id int64) (SpectralClass, error) {
	row := q.db.QueryRow(ctx, getSpectralClass, id)
	var i SpectralClass
	err := row.Scan(
		&i.ID,
		&i.DtCreated,
		&i.DtUpdated,
		&i.Letter,
		&i.Subtype,
		&i.Name,
		&i.MinTemp,
		&i.MaxTemp,
		&i.MinMass,
		&i.MaxMass,
		&i.MinLuminosity,
		&i.MaxLuminosity,
		&i.MinRadius,
		&i.MaxRadius,
	)
	return i, err
}

const getSpectralClassByName = `-- name: GetSpectralClassByName :one
SELECT id, dt_created, dt_updated, letter, subtype, name, min_temp, max_temp, min_mass, max_mass, min_luminosity, max_luminosity, min_radius, max_radius FROM spectral_class WHERE letter = $1 AND subtype = $2
`

type GetSpectralClassByNameParams struct {
	Letter  string `json:"letter"`
	Subtype int16  `json:"subtype"`
}

func (q *Queries) GetSpectralClassByName(ctx context.Context, arg GetSpectralClassByNameParams) (SpectralClass, error) {
	row := q.db.QueryRow(ctx, getSpectralClassByName, arg.Letter, arg.Subtype)
	var i SpectralClass
	err := row.Scan(
		&i.ID,
		&i.DtCreated,
		&i.DtUpdated,
		&i.Letter,
		&i.Subtype,
		&i.Name,
		&i.MinTemp,
		&i.MaxTemp,
		&i.MinMass,
		&i.MaxMass,
		&i.MinLuminosity,
		&i.MaxLuminosity,
		&i.MinRadius,
		&i.MaxRadius,
	)
	return i, err
}

const getStar = `-- name: GetStar :one


SELECT s.id, s.dt_created, s.dt_updated,
       s.name,
       s.id_spectral_class, s.id_luminosity_class, s.id_lifecycle_stage,
       s.mass, s.radius, s.temp, s.luminosity, s.metallicity, s.age,
       s.flare_frequency, s.solar_wind, s.variability,
       s.habitable_inner, s.habitable_outer, s.frost_line,
       s.pos_x, s.pos_y, s.pos_z,
       sc.letter, sc.subtype, sc.name AS spectral_name,
       lc.numeral AS luminosity_numeral, lc.name AS luminosity_name,
       ls.name AS lifecycle_name, ls.is_active
FROM star s
JOIN spectral_class sc ON sc.id = s.id_spectral_class
JOIN luminosity_class lc ON lc.id = s.id_luminosity_class
JOIN lifecycle_stage ls ON ls.id = s.id_lifecycle_stage
WHERE s.id = $1
`

type GetStarRow struct {
	ID                int64              `json:"id"`
	DtCreated         pgtype.Timestamptz `json:"dt_created"`
	DtUpdated         pgtype.Timestamptz `json:"dt_updated"`
	Name              string             `json:"name"`
	IDSpectralClass   int64              `json:"id_spectral_class"`
	IDLuminosityClass int64              `json:"id_luminosity_class"`
	IDLifecycleStage  int64              `json:"id_lifecycle_stage"`
	Mass              int32              `json:"mass"`
	Radius            int32              `json:"radius"`
	Temp              int32              `json:"temp"`
	Luminosity        int32              `json:"luminosity"`
	Metallicity       int32              `json:"metallicity"`
	Age               int32              `json:"age"`
	FlareFrequency    int16              `json:"flare_frequency"`
	SolarWind         int16              `json:"solar_wind"`
	Variability       int16              `json:"variability"`
	HabitableInner    int32              `json:"habitable_inner"`
	HabitableOuter    int32              `json:"habitable_outer"`
	FrostLine         int32              `json:"frost_line"`
	PosX              int32              `json:"pos_x"`
	PosY              int32              `json:"pos_y"`
	PosZ              int32              `json:"pos_z"`
	Letter            string             `json:"letter"`
	Subtype           int16              `json:"subtype"`
	SpectralName      string             `json:"spectral_name"`
	LuminosityNumeral string             `json:"luminosity_numeral"`
	LuminosityName    string             `json:"luminosity_name"`
	LifecycleName     string             `json:"lifecycle_name"`
	IsActive          bool               `json:"is_active"`
}

// ============================================================
// XANDARIS — Star Service Queries
// ============================================================
// Convention: geometry column (pos) is NEVER selected.
// All reads use pos_x, pos_y, pos_z integer columns.
// All spatial WHERE clauses reference pos for index acceleration.
// All writes set pos_x, pos_y, pos_z; the generated column handles the rest.
// ============================================================
// ===================
// STARS
// ===================
func (q *Queries) GetStar(ctx context.Context, id int64) (GetStarRow, error) {
	row := q.db.QueryRow(ctx, getStar, id)
	var i GetStarRow
	err := row.Scan(
		&i.ID,
		&i.DtCreated,
		&i.DtUpdated,
		&i.Name,
		&i.IDSpectralClass,
		&i.IDLuminosityClass,
		&i.IDLifecycleStage,
		&i.Mass,
		&i.Radius,
		&i.Temp,
		&i.Luminosity,
		&i.Metallicity,
		&i.Age,
		&i.FlareFrequency,
		&i.SolarWind,
		&i.Variability,
		&i.HabitableInner,
		&i.HabitableOuter,
		&i.FrostLine,
		&i.PosX,
		&i.PosY,
		&i.PosZ,
		&i.Letter,
		&i.Subtype,
		&i.SpectralName,
		&i.LuminosityNumeral,
		&i.LuminosityName,
		&i.LifecycleName,
		&i.IsActive,
	)
	return i, err
}

const getStellarEnvironment = `-- name: GetStellarEnvironment :one

SELECT
    sys.id AS system_id,
    sys.name AS system_name,
    sys.pos_x, sys.pos_y, sys.pos_z,
    s.id AS primary_star_id,
    s.temp, s.luminosity, s.mass AS star_mass,
    s.metallicity,
    s.habitable_inner, s.habitable_outer, s.frost_line,
    s.flare_frequency, s.solar_wind,
    sc.name AS spectral_name,
    ls.name AS lifecycle_name, ls.is_active
FROM system sys
JOIN system_star ss ON ss.id_system = sys.id AND ss.is_primary = TRUE
JOIN star s ON s.id = ss.id_star
JOIN spectral_class sc ON sc.id = s.id_spectral_class
JOIN lifecycle_stage ls ON ls.id = s.id_lifecycle_stage
WHERE sys.id = $1
`

type GetStellarEnvironmentRow struct {
	SystemID       int64  `json:"system_id"`
	SystemName     string `json:"system_name"`
	PosX           int32  `json:"pos_x"`
	PosY           int32  `json:"pos_y"`
	PosZ           int32  `json:"pos_z"`
	PrimaryStarID  int64  `json:"primary_star_id"`
	Temp           int32  `json:"temp"`
	Luminosity     int32  `json:"luminosity"`
	StarMass       int32  `json:"star_mass"`
	Metallicity    int32  `json:"metallicity"`
	HabitableInner int32  `json:"habitable_inner"`
	HabitableOuter int32  `json:"habitable_outer"`
	FrostLine      int32  `json:"frost_line"`
	FlareFrequency int16  `json:"flare_frequency"`
	SolarWind      int16  `json:"solar_wind"`
	SpectralName   string `json:"spectral_name"`
	LifecycleName  string `json:"lifecycle_name"`
	IsActive       bool   `json:"is_active"`
}

// ===================
// STELLAR ENVIRONMENT
// (what the planet service calls)
// ===================
func (q *Queries) GetStellarEnvironment(ctx context.Context, id int64) (GetStellarEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getStellarEnvironment, id)
	var i GetStellarEnvironmentRow
	err := row.Scan(
		&i.SystemID,
		&i.SystemName,
		&i.PosX,
		&i.PosY,
		&i.PosZ,
		&i.PrimaryStarID,
		&i.Temp,
		&i.Luminosity,
		&i.StarMass,
		&i.Metallicity,
		&i.HabitableInner,
		&i.HabitableOuter,
		&i.FrostLine,
		&i.FlareFrequency,
		&i.SolarWind,
		&i.SpectralName,
		&i.LifecycleName,
		&i.IsActive,
	)
	return i, err
}

const getSystem = `-- name: GetSystem :one

SELECT id, dt_created, dt_updated, name, pos_x, pos_y, pos_z
FROM system WHERE id = $1
`

type GetSystemRow struct {
	ID        int64              `json:"id"`
	DtCreated pgtype.Timestamptz `json:"dt_created"`
	DtUpdated pgtype.Timestamptz `json:"dt_updated"`
	Name      string             `json:"name"`
	PosX      int32              `json:"pos_x"`
	PosY      int32              `json:"pos_y"`
	PosZ      int32              `json:"pos_z"`
}

// ===================
// SYSTEMS
// ===================
func (q *Queries) GetSystem(ctx context.Context, id int64) (GetSystemRow, error) {
	row := q.db.QueryRow(ctx, getSystem, id)
	var i GetSystemRow
	err := row.Scan(
		&i.ID,
		&i.DtCreated,
		&i.DtUpdated,
		&i.Name,
		&i.PosX,
		&i.PosY,
		&i.PosZ,
	)
	return i, err
}

const getSystemStars = `-- name: GetSystemStars :many
SELECT ss.id_system, ss.id_star, ss.semi_major_axis, ss.eccentricity,
       ss.inclination, ss.orbital_period, ss.is_primary,
       s.name AS star_name, s.mass, s.radius, s.temp, s.luminosity,
       s.habitable_inner, s.habitable_outer, s.frost_line,
       s.flare_frequency, s.solar_wind,
       s.pos_x, s.pos_y, s.pos_z,
       sc.name AS spectral_name,
       lc.numeral AS luminosity_numeral,
       ls.name AS lifecycle_name
FROM system_star ss
JOIN star s ON s.id = ss.id_star
JOIN spectral_class sc ON sc.id = s.id_spectral_class
JOIN luminosity_class lc ON lc.id = s.id_luminosity_class
JOIN lifecycle_stage ls ON ls.id = s.id_lifecycle_stage
WHERE ss.id_system = $1
ORDER BY ss.is_primary DESC, s.mass DESC
`

type GetSystemStarsRow struct {
	IDSystem          int64  `json:"id_system"`
	IDStar            int64  `json:"id_star"`
	SemiMajorAxis     int32  `json:"semi_major_axis"`
	Eccentricity      int32  `json:"eccentricity"`
	Inclination       int32  `json:"inclination"`
	OrbitalPeriod     int32  `json:"orbital_period"`
	IsPrimary         bool   `json:"is_primary"`
	StarName          string `json:"star_name"`
	Mass              int32  `json:"mass"`
	Radius            int32  `json:"radius"`
	Temp              int32  `json:"temp"`
	Luminosity        int32  `json:"luminosity"`
	HabitableInner    int32  `json:"habitable_inner"`
	HabitableOuter    int32  `json:"habitable_outer"`
	FrostLine         int32  `json:"frost_line"`
	FlareFrequency    int16  `json:"flare_frequency"`
	SolarWind         int16  `json:"solar_wind"`
	PosX              int32  `json:"pos_x"`
	PosY              int32  `json:"pos_y"`
	PosZ              int32  `json:"pos_z"`
	SpectralName      string `json:"spectral_name"`
	LuminosityNumeral string `json:"luminosity_numeral"`
	LifecycleName     string `json:"lifecycle_name"`
}

func (q *Queries) GetSystemStars(ctx context.Context, idSystem int64) ([]GetSystemStarsRow, error) {
	rows, err := q.db.Query(ctx, getSystemStars, idSystem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSystemStarsRow{}
	for rows.Next() {
		var i GetSystemStarsRow
		if err := rows.Scan(
			&i.IDSystem,
			&i.IDStar,
			&i.SemiMajorAxis,
			&i.Eccentricity,
			&i.Inclination,
			&i.OrbitalPeriod,
			&i.IsPrimary,
			&i.StarName,
			&i.Mass,
			&i.Radius,
			&i.Temp,
			&i.Luminosity,
			&i.HabitableInner,
			&i.HabitableOuter,
			&i.FrostLine,
			&i.FlareFrequency,
			&i.SolarWind,
			&i.PosX,
			&i.PosY,
			&i.PosZ,
			&i.SpectralName,
			&i.LuminosityNumeral,
			&i.LifecycleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStar = `-- name: InsertStar :one
INSERT INTO star (
    id, name,
    id_spectral_class, id_luminosity_class, id_lifecycle_stage,
    mass, radius, temp, luminosity, metallicity, age,
    flare_frequency, solar_wind, variability,
    habitable_inner, habitable_outer, frost_line,
    pos_x, pos_y, pos_z
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20
)
RETURNING id, name, mass, radius, temp, luminosity, pos_x, pos_y, pos_z
`

type InsertStarParams struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	IDSpectralClass   int64  `json:"id_spectral_class"`
	IDLuminosityClass int64  `json:"id_luminosity_class"`
	IDLifecycleStage  int64  `json:"id_lifecycle_stage"`
	Mass              int32  `json:"mass"`
	Radius            int32  `json:"radius"`
	Temp              int32  `json:"temp"`
	Luminosity        int32  `json:"luminosity"`
	Metallicity       int32  `json:"metallicity"`
	Age               int32  `json:"age"`
	FlareFrequency    int16  `json:"flare_frequency"`
	SolarWind         int16  `json:"solar_wind"`
	Variability       int16  `json:"variability"`
	HabitableInner    int32  `json:"habitable_inner"`
	HabitableOuter    int32  `json:"habitable_outer"`
	FrostLine         int32  `json:"frost_line"`
	PosX              int32  `json:"pos_x"`
	PosY              int32  `json:"pos_y"`
	PosZ              int32  `json:"pos_z"`
}

type InsertStarRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Mass       int32  `json:"mass"`
	Radius     int32  `json:"radius"`
	Temp       int32  `json:"temp"`
	Luminosity int32  `json:"luminosity"`
	PosX       int32  `json:"pos_x"`
	PosY       int32  `json:"pos_y"`
	PosZ       int32  `json:"pos_z"`
}

func (q *Queries) InsertStar(ctx context.Context, arg InsertStarParams) (InsertStarRow, error) {
	row := q.db.QueryRow(ctx, insertStar,
		arg.ID,
		arg.Name,
		arg.IDSpectralClass,
		arg.IDLuminosityClass,
		arg.IDLifecycleStage,
		arg.Mass,
		arg.Radius,
		arg.Temp,
		arg.Luminosity,
		arg.Metallicity,
		arg.Age,
		arg.FlareFrequency,
		arg.SolarWind,
		arg.Variability,
		arg.HabitableInner,
		arg.HabitableOuter,
		arg.FrostLine,
		arg.PosX,
		arg.PosY,
		arg.PosZ,
	)
	var i InsertStarRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mass,
		&i.Radius,
		&i.Temp,
		&i.Luminosity,
		&i.PosX,
		&i.PosY,
		&i.PosZ,
	)
	return i, err
}

const insertSystem = `-- name: InsertSystem :one
INSERT INTO system (id, name, pos_x, pos_y, pos_z)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, pos_x, pos_y, pos_z
`

type InsertSystemParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	PosX int32  `json:"pos_x"`
	PosY int32  `json:"pos_y"`
	PosZ int32  `json:"pos_z"`
}

type InsertSystemRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	PosX int32  `json:"pos_x"`
	PosY int32  `json:"pos_y"`
	PosZ int32  `json:"pos_z"`
}

func (q *Queries) InsertSystem(ctx context.Context, arg InsertSystemParams) (InsertSystemRow, error) {
	row := q.db.QueryRow(ctx, insertSystem,
		arg.ID,
		arg.Name,
		arg.PosX,
		arg.PosY,
		arg.PosZ,
	)
	var i InsertSystemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PosX,
		&i.PosY,
		&i.PosZ,
	)
	return i, err
}

const insertSystemStar = `-- name: InsertSystemStar :exec
INSERT INTO system_star (
    id_system, id_star, semi_major_axis, eccentricity,
    inclination, orbital_period, is_primary
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSystemStarParams struct {
	IDSystem      int64 `json:"id_system"`
	IDStar        int64 `json:"id_star"`
	SemiMajorAxis int32 `json:"semi_major_axis"`
	Eccentricity  int32 `json:"eccentricity"`
	Inclination   int32 `json:"inclination"`
	OrbitalPeriod int32 `json:"orbital_period"`
	IsPrimary     bool  `json:"is_primary"`
}

func (q *Queries) InsertSystemStar(ctx context.Context, arg InsertSystemStarParams) error {
	_, err := q.db.Exec(ctx, insertSystemStar,
		arg.IDSystem,
		arg.IDStar,
		arg.SemiMajorAxis,
		arg.Eccentricity,
		arg.Inclination,
		arg.OrbitalPeriod,
		arg.IsPrimary,
	)
	return err
}

const listLifecycleStages = `-- name: ListLifecycleStages :many
SELECT id, dt_created, dt_updated, name, is_active, mod_luminosity, mod_temp FROM lifecycle_stage ORDER BY id
`

func (q *Queries) ListLifecycleStages(ctx context.Context) ([]LifecycleStage, error) {
	rows, err := q.db.Query(ctx, listLifecycleStages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LifecycleStage{}
	for rows.Next() {
		var i LifecycleStage
		if err := rows.Scan(
			&i.ID,
			&i.DtCreated,
			&i.DtUpdated,
			&i.Name,
			&i.IsActive,
			&i.ModLuminosity,
			&i.ModTemp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLuminosityClasses = `-- name: ListLuminosityClasses :many
SELECT id, dt_created, dt_updated, numeral, name, mass_modifier, radius_modifier FROM luminosity_class ORDER BY id
`

func (q *Queries) ListLuminosityClasses(ctx context.Context) ([]LuminosityClass, error) {
	rows, err := q.db.Query(ctx, listLuminosityClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LuminosityClass{}
	for rows.Next() {
		var i LuminosityClass
		if err := rows.Scan(
			&i.ID,
			&i.DtCreated,
			&i.DtUpdated,
			&i.Numeral,
			&i.Name,
			&i.MassModifier,
			&i.RadiusModifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpectralClasses = `-- name: ListSpectralClasses :many

SELECT id, dt_created, dt_updated, letter, subtype, name, min_temp, max_temp, min_mass, max_mass, min_luminosity, max_luminosity, min_radius, max_radius FROM spectral_class ORDER BY letter, subtype
`

// ===================
// LOOKUP TABLES
// ===================
func (q *Queries) ListSpectralClasses(ctx context.Context) ([]SpectralClass, error) {
	rows, err := q.db.Query(ctx, listSpectralClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpectralClass{}
	for rows.Next() {
		var i SpectralClass
		if err := rows.Scan(
			&i.ID,
			&i.DtCreated,
			&i.DtUpdated,
			&i.Letter,
			&i.Subtype,
			&i.Name,
			&i.MinTemp,
			&i.MaxTemp,
			&i.MinMass,
			&i.MaxMass,
			&i.MinLuminosity,
			&i.MaxLuminosity,
			&i.MinRadius,
			&i.MaxRadius,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStarLifecycle = `-- name: UpdateStarLifecycle :exec
UPDATE star SET
    id_lifecycle_stage = $2,
    luminosity = $3,
    temp = $4,
    habitable_inner = $5,
    habitable_outer = $6,
    frost_line = $7,
    dt_updated = now()
WHERE id = $1
`

type UpdateStarLifecycleParams struct {
	ID               int64 `json:"id"`
	IDLifecycleStage int64 `json:"id_lifecycle_stage"`
	Luminosity       int32 `json:"luminosity"`
	Temp             int32 `json:"temp"`
	HabitableInner   int32 `json:"habitable_inner"`
	HabitableOuter   int32 `json:"habitable_outer"`
	FrostLine        int32 `json:"frost_line"`
}

func (q *Queries) UpdateStarLifecycle(ctx context.Context, arg UpdateStarLifecycleParams) error {
	_, err := q.db.Exec(ctx, updateStarLifecycle,
		arg.ID,
		arg.IDLifecycleStage,
		arg.Luminosity,
		arg.Temp,
		arg.HabitableInner,
		arg.HabitableOuter,
		arg.FrostLine,
	)
	return err
}
